### ISSUE TITLE
Unix-style (#) comments in lines seems not to be supported

### ISSUE THREAD

**Issue by m45t3r** [benhoyt/inih#40] opened 2015-10-18 05:14 UTC
I don't even know if this is a real issue (I don't have a test case to, well, test), however looking at the source code (that is really clean, this is why I noticed it) it seems you can have ``#``, or Unix-style, comments in blank lines, however not as a line comment (in this case, only ``;`` seems to be supported). 

Why? Because of this line: https://github.com/benhoyt/inih/blob/master/ini.c#L50. You only compare the current char with ``;`` and not ``#``, different from this line https://github.com/benhoyt/inih/blob/master/ini.c#L106.

**Comment by benhoyt** [comment] 2015-10-19 00:58
I know it's a little bit weird, but this is by design. `inih` is compatible with Python's [ConfigParser](https://docs.python.org/2/library/configparser.html) module, which does it this same way -- `#` is only allowed at start of line. This is probably because of compatibility with Windows .INI file parsing, which doesn't recognize `#` at all. So closing this.

**Comment by m45t3r** [comment] 2015-10-19 01:36
Looking at the last Python (3.5) the behavior changed: https://docs.python.org/3.5/library/configparser.html#customizing-parser-behaviour (``inline_comment_prefixes``). This change seems to be from Python 3.2 onwards.

I actually thing the idea of disabling inline comments a great idea, seems to be more consistent than only allowing ``;`` and not ``#`` for inline comments. It should be simple to add support as a compile time to disable inline comments (just #ifdef the code from ``find_char_or_comment`` and leave only the return).

You can even leave this disabled by default, and I don't think it is worth it to add the option to configure the behavior of inline comments (I think this should be pretty hard to do in C using only preprocessors). However the possibility of disabling inline comments seems great to me.

Need to open another issue?

**Comment by benhoyt** [comment] 2015-10-19 01:47
Huh, interesting -- good find. I kinda like the idea of adding a preprocessor option to disable inline comments completely.

**Comment by benhoyt** [comment] 2016-01-02 17:51
This is now done in https://github.com/benhoyt/inih/releases/tag/r34 - you can easily disable inline comments with `-DDINI_ALLOW_INLINE_COMMENTS=0`, or enable handling of both comment characters with `-DINI_INLINE_COMMENT_PREFIXES=";#"`.

**Closed by benhoyt** 2016-01-02 17:51 UTC

**Comment by benhoyt** [comment] 2016-01-02 18:04
Oops, make that [r35](https://github.com/benhoyt/inih/releases/tag/r35) -- there was a small bug in r34 where it always override your `INI_INLINE_COMMENT_PREFIXES`.
